services:
  - type: web
    name: jitabot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: CHANNEL_SECRET
        sync: false
      - key: CHANNEL_ACCESS_TOKEN
        sync: false